Repository oQaris/QChess, pull requests merged in 2021-08, with the labels that each got.

#45 Оптимизация всего + NNNBot
  .github/workflows/action.yml
  client/pom.xml
  client/src/main/java/io/deeplay/qchess/client/service/GameGUIAdapter.java
  client/src/main/java/io/deeplay/qchess/client/service/GameService.java
  game/pom.xml
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/logics/EndGameDetector.java
  game/src/main/java/io/deeplay/qchess/game/logics/MoveSystem.java
  game/src/main/java/io/deeplay/qchess/game/math/GameMath.java
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/BoardState.java
  game/src/main/java/io/deeplay/qchess/game/model/Cell.java
  game/src/main/java/io/deeplay/qchess/game/model/History.java
  game/src/main/java/io/deeplay/qchess/game/model/Move.java
  game/src/main/java/io/deeplay/qchess/game/model/MoveType.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Bishop.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Figure.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/FigureType.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/King.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Knight.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Pawn.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Queen.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Rook.java
  game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
  game/src/test/java/io/deeplay/qchess/game/logics/MoveSystemTest.java
  game/src/test/java/io/deeplay/qchess/game/math/GameMathTest.java
  game/src/test/java/io/deeplay/qchess/game/model/BoardTest.java
  game/src/test/java/io/deeplay/qchess/game/model/HistoryTest.java
  nnnbot/README.md
  nnnbot/pom.xml
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/Main.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/NNNBot.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/NNNBotFactory.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/evaluationfunc/EvaluationFunc.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/evaluationfunc/FigureCountEvaluation.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/SearchFunc.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/MinimaxParallelSearch.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/ParallelSearch.java
  nnnbot/src/main/resources/logback.xml
  nnnbot/src/test/java/io/deeplay/qchess/nnnbot/bot/NNNBotTest.java
  pom.xml
  qbot/pom.xml
  qbot/src/main/java/io/deeplay/qchess/qbot/QBot.java
  server/src/main/java/io/deeplay/qchess/server/database/Room.java
Labels: enhancement, improvement

#47 Просто мусор
  client/src/main/resources/logback-client.xml
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/exceptions/ChessErrorCode.java
  game/src/main/java/io/deeplay/qchess/game/logics/EndGameDetector.java
  game/src/main/java/io/deeplay/qchess/game/logics/MoveSystem.java
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/Move.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Bishop.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Figure.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/King.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Knight.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Pawn.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Queen.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Rook.java
  game/src/test/java/io/deeplay/qchess/game/logics/MoveSystemTest.java
  game/src/test/java/io/deeplay/qchess/game/model/CellTest.java
  game/src/test/java/io/deeplay/qchess/game/model/HistoryTest.java
  game/src/test/java/io/deeplay/qchess/game/model/figures/FigureTest.java
  game/src/test/resources/logback-game.xml
  nnnbot/pom.xml
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/NNNBotFactory.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/evaluationfunc/EvaluationFunc.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/evaluationfunc/FigureCountEvaluation.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/evaluationfunc/MatrixEvaluation.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/MinimaxAlfaBetaPruning.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/MinimaxParallelSearch.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/NegamaxAlfaBetaPruning.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/ParallelSearch.java
  nnnbot/src/test/java/io/deeplay/qchess/nnnbot/bot/NNNBotTest.java
  qbot/src/main/resources/logback-qbot.xml
  server/src/main/resources/logback-server.xml
Labels: enhancement, improvement

#52 Game update
  README.md
  client/src/main/java/io/deeplay/qchess/client/service/GameService.java
  game/src/main/java/io/deeplay/qchess/game/GameSettings.java
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/exceptions/ChessError.java
  game/src/main/java/io/deeplay/qchess/game/exceptions/ChessErrorCode.java
  game/src/main/java/io/deeplay/qchess/game/exceptions/ChessException.java
  game/src/main/java/io/deeplay/qchess/game/logics/EndGameDetector.java
  game/src/main/java/io/deeplay/qchess/game/logics/MoveSystem.java
  game/src/main/java/io/deeplay/qchess/game/math/GameMath.java
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/BoardState.java
  game/src/main/java/io/deeplay/qchess/game/model/Cell.java
  game/src/main/java/io/deeplay/qchess/game/model/History.java
  game/src/main/java/io/deeplay/qchess/game/model/Move.java
  game/src/main/java/io/deeplay/qchess/game/model/MoveType.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Bishop.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Figure.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/FigureType.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/King.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Knight.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Pawn.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Queen.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Rook.java
  game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
  game/src/main/java/io/deeplay/qchess/game/player/ConsolePlayer.java
  game/src/main/java/io/deeplay/qchess/game/player/Player.java
  game/src/main/java/io/deeplay/qchess/game/player/RandomBot.java
  game/src/main/java/io/deeplay/qchess/game/player/RemotePlayer.java
  game/src/main/java/io/deeplay/qchess/game/service/NotationService.java
  game/src/test/java/io/deeplay/qchess/game/logics/MoveSystemTest.java
  game/src/test/java/io/deeplay/qchess/game/math/GameMathTest.java
  game/src/test/java/io/deeplay/qchess/game/model/HistoryTest.java
  game/src/test/java/io/deeplay/qchess/game/model/figures/FigureTest.java
  misc/screen.jpg
  misc/screen.png
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/MinimaxAlfaBetaPruning.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/searchfunc/parallelsearch/ParallelSearch.java
  nnnbot/src/test/java/io/deeplay/qchess/nnnbot/bot/NNNBotTest.java
  qbot/src/main/java/io/deeplay/qchess/qbot/QBot.java
  server/pom.xml
  server/src/main/java/io/deeplay/qchess/server/service/MatchMaking.java
Labels: improvement

#53 Arena feature
  client/src/main/java/io/deeplay/qchess/client/service/GameService.java
  core/pom.xml
  core/src/main/java/io/deeplay/qchess/core/Arena.java
  core/src/main/java/io/deeplay/qchess/core/Main.java
  core/src/main/java/io/deeplay/qchess/core/TimeWrapper.java
  core/src/main/resources/logback.xml
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
  game/src/main/java/io/deeplay/qchess/game/player/ConsolePlayer.java
  game/src/main/java/io/deeplay/qchess/game/player/RandomBot.java
  game/src/main/java/io/deeplay/qchess/game/player/RemotePlayer.java
  game/src/test/java/io/deeplay/qchess/game/model/HistoryTest.java
  nnnbot/src/main/java/io/deeplay/qchess/nnnbot/bot/NNNBot.java
  qbot/src/main/java/io/deeplay/qchess/qbot/QBot.java
  server/src/main/java/io/deeplay/qchess/server/service/MatchMaking.java
Labels: enhancement

#55 Client Configuration
  client/pom.xml
  client/src/main/java/io/deeplay/qchess/client/service/config/ClientSettings.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ConfigException.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ConfigExceptionErrorCode.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
  client/src/main/resources/client_configuration.conf
  client/src/test/java/io/deeplay/qchess/client/service/config/ClientSettingsTest.java
  client/src/test/java/io/deeplay/qchess/client/service/config/ConfigServiceTest.java
  client/src/test/resources/00_test_absent_ip.conf
  client/src/test/resources/04_test_absent_port.conf
  client/src/test/resources/07_test_absent_boolean.conf
  client/src/test/resources/09_test_absent_player_type.conf
  client/src/test/resources/11_test_absent_path.conf
  client/src/test/resources/13_test_absent_color.conf
  client/src/test/resources/15_test_empty_ip.conf
  client/src/test/resources/16_test_empty_port.conf
  client/src/test/resources/17_test_empty_boolean.conf
  client/src/test/resources/18_test_empty_player_type.conf
  client/src/test/resources/19_test_empty_path.conf
  client/src/test/resources/20_test_empty_color.conf
  client/src/test/resources/50_test_complete.conf
  client/src/test/resources/51_test_complete.conf
  client/src/test/resources/52_test_complete.conf
  client/src/test/resources/53_test_complete.conf
Labels: enhancement

#58 Добавлена возможность выбора цвета на сервере
  client/src/main/java/io/deeplay/qchess/client/controller/ClientController.java
  client/src/main/java/io/deeplay/qchess/client/dao/GameDAO.java
  client/src/main/java/io/deeplay/qchess/client/database/Database.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseMyColorFrame.java
  clientserverconversation/src/main/java/io/deeplay/qchess/clientserverconversation/dto/clienttoserver/FindGameDTO.java
  game/src/main/java/io/deeplay/qchess/game/player/ConsolePlayer.java
  game/src/main/java/io/deeplay/qchess/game/player/PlayerType.java
  game/src/main/java/io/deeplay/qchess/game/player/RemotePlayer.java
  server/src/main/java/io/deeplay/qchess/server/dao/GameDAO.java
  server/src/main/java/io/deeplay/qchess/server/database/Database.java
  server/src/main/java/io/deeplay/qchess/server/database/Room.java
  server/src/main/java/io/deeplay/qchess/server/service/GameService.java
  server/src/main/java/io/deeplay/qchess/server/service/MatchMaking.java
Labels: enhancement

#60 Конфиги для сервера
  client/src/main/java/io/deeplay/qchess/client/service/config/ClientSettings.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ConfigExceptionErrorCode.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
  server/pom.xml
  server/src/main/java/io/deeplay/qchess/server/service/config/ConfigException.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ConfigExceptionErrorCode.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ConfigService.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ServerSettings.java
  server/src/main/resources/server_configuration.conf
  server/src/test/java/io/deeplay/qchess/server/service/config/ConfigServiceTest.java
Labels: enhancement

#61 Улучшения Арены
  core/src/main/java/io/deeplay/qchess/core/Arena.java
  core/src/main/java/io/deeplay/qchess/core/ArenaStats.java
  core/src/main/java/io/deeplay/qchess/core/Main.java
  core/src/main/java/io/deeplay/qchess/core/TimeWrapper.java
  core/src/main/resources/logback.xml
Labels: improvement, enhancement

#62 Добавлены final ВЕЗДЕ
  clientserverconversation/src/main/java/io/deeplay/qchess/clientserverconversation/dto/main/ClientToServerType.java
  clientserverconversation/src/main/java/io/deeplay/qchess/clientserverconversation/dto/main/ServerToClientType.java
  clientserverconversation/src/main/java/io/deeplay/qchess/clientserverconversation/service/SerializationService.java
  game/src/main/java/io/deeplay/qchess/game/GameSettings.java
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/logics/MoveSystem.java
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/BoardState.java
  game/src/main/java/io/deeplay/qchess/game/model/Cell.java
  game/src/main/java/io/deeplay/qchess/game/model/History.java
  game/src/main/java/io/deeplay/qchess/game/model/Move.java
  game/src/main/java/io/deeplay/qchess/game/player/ConsolePlayer.java
  game/src/main/java/io/deeplay/qchess/game/player/Player.java
  game/src/main/java/io/deeplay/qchess/game/player/RandomBot.java
  game/src/main/java/io/deeplay/qchess/game/player/RemotePlayer.java
  server/src/main/java/io/deeplay/qchess/server/LocalHost.java
  server/src/main/java/io/deeplay/qchess/server/Main.java
  server/src/main/java/io/deeplay/qchess/server/controller/ServerController.java
  server/src/main/java/io/deeplay/qchess/server/dao/ConnectionControlDAO.java
  server/src/main/java/io/deeplay/qchess/server/dao/GameDAO.java
  server/src/main/java/io/deeplay/qchess/server/database/Database.java
  server/src/main/java/io/deeplay/qchess/server/database/Room.java
  server/src/main/java/io/deeplay/qchess/server/exceptions/ServerErrorCode.java
  server/src/main/java/io/deeplay/qchess/server/exceptions/ServerException.java
  server/src/main/java/io/deeplay/qchess/server/handlers/ClientHandler.java
  server/src/main/java/io/deeplay/qchess/server/handlers/ClientHandlerManager.java
  server/src/main/java/io/deeplay/qchess/server/handlers/ClientRequestHandler.java
  server/src/main/java/io/deeplay/qchess/server/service/ChatService.java
  server/src/main/java/io/deeplay/qchess/server/service/ConnectionControlService.java
  server/src/main/java/io/deeplay/qchess/server/service/GameService.java
  server/src/main/java/io/deeplay/qchess/server/service/MatchMaking.java
  server/src/main/java/io/deeplay/qchess/server/service/ServerCommandService.java
  server/src/main/java/io/deeplay/qchess/server/service/StatisticService.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ConfigService.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ServerSettings.java
  server/src/main/java/io/deeplay/qchess/server/view/ServerConsole.java
Labels: improvement

#64 Reformatting - расстановка final
  client/src/main/java/io/deeplay/qchess/client/LocalClient.java
  client/src/main/java/io/deeplay/qchess/client/Main.java
  client/src/main/java/io/deeplay/qchess/client/controller/ClientController.java
  client/src/main/java/io/deeplay/qchess/client/dao/GameDAO.java
  client/src/main/java/io/deeplay/qchess/client/dao/SessionDAO.java
  client/src/main/java/io/deeplay/qchess/client/database/Database.java
  client/src/main/java/io/deeplay/qchess/client/exceptions/ClientErrorCode.java
  client/src/main/java/io/deeplay/qchess/client/exceptions/ClientException.java
  client/src/main/java/io/deeplay/qchess/client/handlers/InputTrafficHandler.java
  client/src/main/java/io/deeplay/qchess/client/handlers/TrafficRequestHandler.java
  client/src/main/java/io/deeplay/qchess/client/service/ChatService.java
  client/src/main/java/io/deeplay/qchess/client/service/ClientCommandService.java
  client/src/main/java/io/deeplay/qchess/client/service/GameGUIAdapter.java
  client/src/main/java/io/deeplay/qchess/client/service/GameService.java
  client/src/main/java/io/deeplay/qchess/client/service/SessionService.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ClientSettings.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ConfigExceptionErrorCode.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ConfigService.java
  client/src/main/java/io/deeplay/qchess/client/view/console/ClientConsole.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseMyColorFrame.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/ChooseStyleFrame.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/ClientGUI.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/CloseFrameListener.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/ConnectFrame.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/MainFrame.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/MessageFrame.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/ViewCell.java
  client/src/main/java/io/deeplay/qchess/client/view/model/ViewBoard.java
  client/src/main/java/io/deeplay/qchess/client/view/model/ViewFigure.java
  client/src/test/java/io/deeplay/qchess/client/service/config/ClientSettingsTest.java
  client/src/test/java/io/deeplay/qchess/client/service/config/ConfigServiceTest.java
  clientserverconversation/src/main/java/io/deeplay/qchess/clientserverconversation/dto/main/ClientToServerType.java
  clientserverconversation/src/main/java/io/deeplay/qchess/clientserverconversation/dto/main/ServerToClientType.java
  clientserverconversation/src/main/java/io/deeplay/qchess/clientserverconversation/service/SerializationService.java
  core/src/main/java/io/deeplay/qchess/core/Main.java
  game/src/main/java/io/deeplay/qchess/game/model/BoardState.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Figure.java
  game/src/test/java/io/deeplay/qchess/game/Main.java
  game/src/test/java/io/deeplay/qchess/game/logics/EndGameDetectorTest.java
  game/src/test/java/io/deeplay/qchess/game/logics/MoveSystemTest.java
  game/src/test/java/io/deeplay/qchess/game/math/GameMathTest.java
  game/src/test/java/io/deeplay/qchess/game/model/BoardTest.java
  game/src/test/java/io/deeplay/qchess/game/model/CellTest.java
  game/src/test/java/io/deeplay/qchess/game/model/HistoryTest.java
  game/src/test/java/io/deeplay/qchess/game/player/BotTest.java
  game/src/test/java/io/deeplay/qchess/game/service/NotationServiceTest.java
  server/src/main/java/io/deeplay/qchess/server/dao/GameDAO.java
  server/src/main/java/io/deeplay/qchess/server/database/Database.java
  server/src/main/java/io/deeplay/qchess/server/handlers/ClientHandler.java
  server/src/main/java/io/deeplay/qchess/server/handlers/ClientHandlerManager.java
  server/src/main/java/io/deeplay/qchess/server/service/ChatService.java
  server/src/main/java/io/deeplay/qchess/server/service/ConnectionControlService.java
  server/src/main/java/io/deeplay/qchess/server/service/GameService.java
  server/src/main/java/io/deeplay/qchess/server/service/MatchMaking.java
  server/src/main/java/io/deeplay/qchess/server/service/StatisticService.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ConfigExceptionErrorCode.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ConfigService.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ServerSettings.java
  server/src/test/java/io/deeplay/qchess/server/service/config/ConfigServiceTest.java
Labels: improvement

#56 Обновлен способ собирания .jar
  client/pom.xml
  client/src/main/java/io/deeplay/qchess/client/Main.java
  client/src/main/java/io/deeplay/qchess/client/service/GameService.java
  client/src/main/java/io/deeplay/qchess/client/service/config/ClientSettings.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
  client/src/main/resources/client_configuration.conf
  client/src/main/resources/logback-client.xml
  client/src/test/java/io/deeplay/qchess/client/service/config/ClientSettingsTest.java
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/test/resources/logback.xml
  server/pom.xml
  server/src/main/java/io/deeplay/qchess/server/Main.java
  server/src/main/java/io/deeplay/qchess/server/service/config/ServerSettings.java
  server/src/main/resources/logback-server.xml
  server/src/main/resources/server_configuration.conf
Labels: improvement

#63 Подсчёт рейтинга Эло для игроков
  core/pom.xml
  core/src/main/java/io/deeplay/qchess/core/Arena.java
  core/src/main/java/io/deeplay/qchess/core/ArenaStats.java
  core/src/main/java/io/deeplay/qchess/core/RatingELO.java
  elo_rating.txt
  game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
  game/src/main/java/io/deeplay/qchess/game/player/RandomBot.java
  game/src/test/java/io/deeplay/qchess/game/player/BotTest.java
Labels: enhancement

#66 Исправление создания ботов
  client/src/main/java/io/deeplay/qchess/client/service/GameService.java
  game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
  server/src/main/java/io/deeplay/qchess/server/service/MatchMaking.java
Labels: Bugfix

#67 Исправлено сбрасывание комнат
  server/src/main/java/io/deeplay/qchess/server/database/Room.java
  server/src/main/java/io/deeplay/qchess/server/service/GameService.java
Labels: Bugfix

#69 Оптимизация очищения истории
  game/src/main/java/io/deeplay/qchess/game/logics/MoveSystem.java
  game/src/main/java/io/deeplay/qchess/game/model/History.java
  game/src/test/java/io/deeplay/qchess/game/logics/EndGameDetectorTest.java
Labels: improvement

#70 Изменены id типов фигур - теперь они совместимы с PeSTO
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Figure.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/FigureType.java
Labels: improvement

#71 Добавлены javadocs в движок игры
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/logics/EndGameDetector.java
  game/src/main/java/io/deeplay/qchess/game/logics/MoveSystem.java
  game/src/main/java/io/deeplay/qchess/game/math/GameMath.java
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/Cell.java
  game/src/main/java/io/deeplay/qchess/game/model/History.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Figure.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/FigureType.java
Labels: improvement

#72 Небольшие оптимизации
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/logics/EndGameDetector.java
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/History.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Bishop.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Figure.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/FigureType.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/King.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Knight.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Pawn.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Queen.java
  game/src/main/java/io/deeplay/qchess/game/model/figures/Rook.java
  game/src/test/java/io/deeplay/qchess/game/model/BoardTest.java
  game/src/test/java/io/deeplay/qchess/game/model/HistoryTest.java
Labels: improvement

#68 Gui fix
  client/src/main/java/io/deeplay/qchess/client/controller/ClientController.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/CloseFrameListener.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/MainFrame.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/MessageFrame.java
  client/src/main/java/io/deeplay/qchess/client/view/gui/Table.java
  client/src/main/java/io/deeplay/qchess/client/view/model/ViewFigure.java
Labels: Bugfix

#73 Optimization update + Game Engine
  game/pom.xml
  game/src/main/java/io/deeplay/qchess/game/GameSettings.java
  game/src/main/java/io/deeplay/qchess/game/Selfplay.java
  game/src/main/java/io/deeplay/qchess/game/features/ITranspositionTable.java
  game/src/main/java/io/deeplay/qchess/game/logics/EndGameDetector.java
  game/src/main/java/io/deeplay/qchess/game/logics/MoveSystem.java
  game/src/main/java/io/deeplay/qchess/game/model/Board.java
  game/src/main/java/io/deeplay/qchess/game/model/BoardState.java
  game/src/main/java/io/deeplay/qchess/game/model/Cell.java
  game/src/main/java/io/deeplay/qchess/game/model/History.java
  game/src/main/java/io/deeplay/qchess/game/model/MoveType.java
  game/src/main/java/io/deeplay/qchess/game/player/AttackBot.java
  game/src/main/java/io/deeplay/qchess/game/player/BotFactory.java
  game/src/main/java/io/deeplay/qchess/game/player/RandomBot.java
  game/src/main/java/io/deeplay/qchess/game/player/TimeWrapper.java
  game/src/test/java/io/deeplay/qchess/game/model/figures/FigureTest.java
  game/src/test/resources/logback-game.xml
Labels: improvement, bugfix
